# -*- coding: utf-8 -*-
"""Selamat Datang di Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# ============================================================
# PRAKTIKUM: BEN 10 BATTLE DATASET
# ============================================================

# ── BAGIAN 1: Install & Import Library ──────────────────────
import pandas as pd
import json

# ── BAGIAN 2: Upload Dataset ke Google Colab ────────────────
from google.colab import files
uploaded = files.upload()   # pilih file ben10_battle_dataset.csv

# ── BAGIAN 3: Baca Dataset ───────────────────────────────────
df = pd.read_csv('ben10_battle_dataset.csv')

# ── BAGIAN 4: Tampilkan Dataset ──────────────────────────────
print("=" * 60)
print("HEAD() — 5 baris pertama:")
print("=" * 60)
print(df.head())

print("\n" + "=" * 60)
print("INFO() — informasi tipe data & nilai kosong:")
print("=" * 60)
df.info()

print("\n" + "=" * 60)
print("SHAPE — jumlah baris dan kolom:")
print("=" * 60)
print(f"Jumlah baris  : {df.shape[0]}")
print(f"Jumlah kolom  : {df.shape[1]}")
print(f"Shape lengkap : {df.shape}")

# ── BAGIAN 5: Jelaskan Struktur Dataset ──────────────────────
print("\n" + "=" * 60)
print("STRUKTUR DATASET:")
print("=" * 60)
print(f"\nTotal baris  : {df.shape[0]}")
print(f"Total kolom  : {df.shape[1]}")
print("\nNama kolom & tipe data:")
print(df.dtypes)
print("\nStatistik deskriptif (kolom numerik):")
print(df.describe())
print("\nJumlah nilai kosong per kolom:")
print(df.isnull().sum())

# ── BAGIAN 6: Buat Struktur Data JSON Secara Manual ──────────
print("\n" + "=" * 60)
print("STRUKTUR DATA JSON (Manual):")
print("=" * 60)

data_json_manual = [
    {
        "battle_id": 1,
        "hero_name": "Heatblast",
        "hero_series": "Original Series",
        "hero_type": "Classic",
        "hero_powers": "Pyrokinesis, Fire Absorption, Flight",
        "hero_total_power": 45.05,
        "hero_combat": 60,
        "hero_speed": 49,
        "hero_durability": 50,
        "hero_intelligence": 56,
        "hero_heat": 100,
        "hero_water": 0,
        "hero_electricity": 15,
        "hero_magic": 0,
        "hero_stealth": 21,
        "villain_name": "Vilgax",
        "villain_species": "Chimera Sui Generis",
        "villain_affiliation": "Solo",
        "villain_powers": "Super Strength, Laser Eyes, Sword Mastery",
        "villain_total_power": 62.5,
        "villain_combat": 95,
        "villain_speed": 40,
        "villain_durability": 95,
        "villain_intelligence": 80,
        "villain_heat": 60,
        "villain_water": 20,
        "villain_electricity": 15,
        "villain_magic": 10,
        "villain_stealth": 15,
        "terrain": "Underwater",
        "battle_type": "Ambush",
        "hero_terrain_bonus": 0.92,
        "villain_terrain_bonus": 0.964,
        "hero_win_probability": 0.4929,
        "battle_outcome": "Loss",
        "difficulty_rating": "Hard"
    },
    {
        "battle_id": 2,
        "hero_name": "Heatblast",
        "hero_series": "Original Series",
        "hero_type": "Classic",
        "hero_powers": "Pyrokinesis, Fire Absorption, Flight",
        "hero_total_power": 45.05,
        "hero_combat": 60,
        "hero_speed": 49,
        "hero_durability": 50,
        "hero_intelligence": 56,
        "hero_heat": 100,
        "hero_water": 0,
        "hero_electricity": 15,
        "hero_magic": 0,
        "hero_stealth": 21,
        "villain_name": "Vilgax",
        "villain_species": "Chimera Sui Generis",
        "villain_affiliation": "Solo",
        "villain_powers": "Super Strength, Laser Eyes, Sword Mastery",
        "villain_total_power": 62.5,
        "villain_combat": 95,
        "villain_speed": 40,
        "villain_durability": 95,
        "villain_intelligence": 80,
        "villain_heat": 60,
        "villain_water": 20,
        "villain_electricity": 15,
        "villain_magic": 10,
        "villain_stealth": 15,
        "terrain": "Desert",
        "battle_type": "1v1",
        "hero_terrain_bonus": 1.031,
        "villain_terrain_bonus": 1.008,
        "hero_win_probability": 0.4887,
        "battle_outcome": "Draw",
        "difficulty_rating": "Hard"
    },
    {
        "battle_id": 3,
        "hero_name": "Four Arms",
        "hero_series": "Original Series",
        "hero_type": "Classic",
        "hero_powers": "Super Strength, Durability, Sonic Clap",
        "hero_total_power": 55.0,
        "hero_combat": 85,
        "hero_speed": 40,
        "hero_durability": 90,
        "hero_intelligence": 45,
        "hero_heat": 30,
        "hero_water": 10,
        "hero_electricity": 10,
        "hero_magic": 0,
        "hero_stealth": 5,
        "villain_name": "Kevin 11",
        "villain_species": "Human Mutant",
        "villain_affiliation": "Solo",
        "villain_powers": "Power Absorption, Mutation",
        "villain_total_power": 50.0,
        "villain_combat": 80,
        "villain_speed": 45,
        "villain_durability": 75,
        "villain_intelligence": 60,
        "villain_heat": 20,
        "villain_water": 10,
        "villain_electricity": 50,
        "villain_magic": 0,
        "villain_stealth": 15,
        "terrain": "City",
        "battle_type": "1v1",
        "hero_terrain_bonus": 1.0,
        "villain_terrain_bonus": 1.0,
        "hero_win_probability": 0.62,
        "battle_outcome": "Win",
        "difficulty_rating": "Medium"
    },
    {
        "battle_id": 4,
        "hero_name": "XLR8",
        "hero_series": "Original Series",
        "hero_type": "Classic",
        "hero_powers": "Super Speed, Tail Whip, Wall Running",
        "hero_total_power": 48.0,
        "hero_combat": 55,
        "hero_speed": 100,
        "hero_durability": 40,
        "hero_intelligence": 60,
        "hero_heat": 10,
        "hero_water": 5,
        "hero_electricity": 10,
        "hero_magic": 0,
        "hero_stealth": 40,
        "villain_name": "Hex",
        "villain_species": "Human",
        "villain_affiliation": "Solo",
        "villain_powers": "Magic, Staff of Ages, Levitation",
        "villain_total_power": 58.0,
        "villain_combat": 65,
        "villain_speed": 35,
        "villain_durability": 55,
        "villain_intelligence": 90,
        "villain_heat": 15,
        "villain_water": 10,
        "villain_electricity": 15,
        "villain_magic": 95,
        "villain_stealth": 20,
        "terrain": "Forest",
        "battle_type": "Ambush",
        "hero_terrain_bonus": 1.05,
        "villain_terrain_bonus": 0.95,
        "hero_win_probability": 0.45,
        "battle_outcome": "Loss",
        "difficulty_rating": "Hard"
    },
    {
        "battle_id": 5,
        "hero_name": "Diamondhead",
        "hero_series": "Original Series",
        "hero_type": "Classic",
        "hero_powers": "Crystal Projectiles, Hardened Body, Refraction",
        "hero_total_power": 52.0,
        "hero_combat": 75,
        "hero_speed": 35,
        "hero_durability": 95,
        "hero_intelligence": 55,
        "hero_heat": 20,
        "hero_water": 15,
        "hero_electricity": 80,
        "hero_magic": 0,
        "hero_stealth": 10,
        "villain_name": "Clancy",
        "villain_species": "Human Mutant",
        "villain_affiliation": "Solo",
        "villain_powers": "Insect Control, Swarm Attack",
        "villain_total_power": 40.0,
        "villain_combat": 50,
        "villain_speed": 55,
        "villain_durability": 45,
        "villain_intelligence": 55,
        "villain_heat": 10,
        "villain_water": 10,
        "villain_electricity": 10,
        "villain_magic": 0,
        "villain_stealth": 60,
        "terrain": "Jungle",
        "battle_type": "Team Battle",
        "hero_terrain_bonus": 0.98,
        "villain_terrain_bonus": 1.10,
        "hero_win_probability": 0.70,
        "battle_outcome": "Win",
        "difficulty_rating": "Easy"
    }
]

# Tampilkan JSON
print(json.dumps(data_json_manual, indent=4))

# ── BAGIAN 7: Konversi JSON → DataFrame → CSV ────────────────
print("\n" + "=" * 60)
print("KONVERSI JSON ke CSV:")
print("=" * 60)

df_dari_json = pd.DataFrame(data_json_manual)
print("DataFrame hasil konversi dari JSON:")
print(df_dari_json)

# Simpan ke file CSV
nama_file_csv = 'ben10_manual_json_to_csv.csv'
df_dari_json.to_csv(nama_file_csv, index=False)
print(f"\nFile CSV berhasil disimpan sebagai: {nama_file_csv}")

# ── BAGIAN 8: Download File CSV ──────────────────────────────
print("\n" + "=" * 60)
print("DOWNLOAD FILE CSV:")
print("=" * 60)
files.download(nama_file_csv)
print("File sedang diunduh... Upload ke GitHub secara manual.")

# ── SELESAI ──────────────────────────────────────────────────
print("\n" + "=" * 60)
print("RINGKASAN STRUKTUR DATASET ben10_battle_dataset.csv")
print("=" * 60)

print("Jumlah Baris   :", df.shape[0], "baris")
print("Jumlah Kolom   :", df.shape[1], "kolom")
print("")
print("Kelompok Kolom:")
print("  - Identifikasi     : battle_id")
print("  - Data Hero        : hero_name, hero_series, hero_type, hero_powers,")
print("                       hero_total_power, hero_combat, hero_speed,")
print("                       hero_durability, hero_intelligence,")
print("                       hero_heat, hero_water, hero_electricity,")
print("                       hero_magic, hero_stealth  (14 kolom)")
print("  - Data Villain     : villain_name, villain_species, villain_affiliation,")
print("                       villain_powers, villain_total_power, villain_combat,")
print("                       villain_speed, villain_durability, villain_intelligence,")
print("                       villain_heat, villain_water, villain_electricity,")
print("                       villain_magic, villain_stealth  (14 kolom)")
print("  - Data Pertarungan : terrain, battle_type, hero_terrain_bonus,")
print("                       villain_terrain_bonus, hero_win_probability,")
print("                       battle_outcome, difficulty_rating  (7 kolom)")
print("")
print("Tipe Data:")
print("  - int64   : kolom statistik numerik (combat, speed, dll.)")
print("  - float64 : kolom desimal (total_power, bonus, probability)")
print("  - object  : kolom teks (nama, powers, outcome, dll.)")

